library(shiny)
library(ggplot2)
library(readr)
library(here)

dataset <- read_csv(here("open_data", "rainfall", "aggreg_edinburgh_rainfall.csv"))
num_of_dates <- nrow(unique(dataset['Timestamp']))


fluidPage(
  
  titlePanel("Edinburgh Rainfall according to D4CAE"),
  
  sidebarPanel(
    # Could have textInput or numericInput but 
    # probably better stick with controlled vocab autogenerated ie selectInput
    sliderInput(inputId = 'timestamp_slider', label = "The dates", min=1, max=num_of_dates,
                value=nrow(dataset), step=10, round=0),
    
    selectInput(inputId = 'data_column_dropdown', label = 'rainfall aspects', names(dataset)),
    selectInput('rain_station', 'Rain station name', c('None', unique(dataset[["rain_station"]]))),
    
    checkboxInput('jitter', 'Jitter'),
    checkboxInput('smooth', 'Smooth'),
    
    selectInput('facet_row', 'Facet Row', c(None='.', names(dataset))),
    selectInput('facet_col', 'Facet Column', c(None='.', names(dataset)))
  ),
  
  mainPanel(
    plotOutput('plot')
  )
)